export default {
  SIGNIN_REQUEST: '@auth/SIGNIN_REQUEST',
  SIGNIN_SUCCESS: '@auth/SIGNIN_SUCCESS',
  SIGNOUT: '@auth/SIGNOUT',
  SKIP_SIGNIN: '@auth/SKIP_SIGNIN',
  SIGNIN_BY_REGISTER: '@auth/SIGIN_BY_REGISTER',
  SET_AUTHENTICATED: '@auth/SET_AUTHENTICATED',
};
